
# ------------------------------------------------------------------------------ CONFIG

variables:
  BRANCH: $CI_COMMIT_REF_NAME
  GIT_SUBMODULE_STRATEGY: recursive

image:
  name: zouloux/docker-ci-php-node

# Keep those files between builds
cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .composer-cache
    - .cache
    - node_modules
    - vendor

stages:
  - deploy

# ------------------------------------------------------------------------------ BUILD TEMPLATE

.BuildScript: &BuildScript
  - "# --- SETUP ENV ---"
  - cp ".env.$ENV" .env
  - "# --- INSTALL NODE DEPENDENCIES ---"
  - npm ci
  - "# --- VERSION CACHE BUSTING"
  - npm run create-version
  - "# --- INSTALL COMPOSER DEPENDENCIES ---"
  - composer config -g cache-dir "$(pwd)/.composer-cache"
  - composer install --ignore-platform-reqs
  - "# --- BUILD ASSETS ---"
  - npm run build

# ------------------------------------------------------------------------------ BEFORE SCRIPT

# Install SSH keys before each build
default:
  before_script:
    - "# --- INSTALL SSH KEYS ---"
    - mkdir -p .ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "-----BEGIN OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
    - echo $SSH_PRIVATE | tr " " "\n" >> ~/.ssh/id_rsa
    - echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_rsa
    - echo $SSH_PUBLIC > ~/.ssh/id_rsa.pub
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
    - eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa

# ------------------------------------------------------------------------------ STAGING DEPLOY

job:deploy_staging:
  stage: deploy
  # Execute this job for master and root branches
  except:
    - /^(.+)/(.+)$/
  variables:
    ENV: "staging"
  script:
    - *BuildScript
    - "# --- PUSH TO STAGING SERVER"
    - ./node_modules/.bin/chimera-ci push --host $CHIMERA_HOST --branch $BRANCH

# ------------------------------------------------------------------------------ PRODUCTION DEPLOY

job:deploy_production:
  when: manual
  stage: deploy
  only:
    - master
  variables:
    ENV: "production"
    DEPLOY_HOST: "user@host"
    PROJECT_NAME: "project-name"
  script :
    - *BuildScript
    - |
      echo "--- PUSH TO PRODUCTION ---"
      ./node_modules/.bin/chimera-ci push \
        --host $DEPLOY_HOST --password $DEPLOY_PASSWORD \
        --install --no-docker
    #--after-script "ln -sf '~/chimera/projects/${PROJECT_NAME}/master/trunk/public' '~/${PROJECT_NAME}'"
