version: "3.7"

services:

  {{name}}-ddap :
    image: "zouloux/docker-debian-apache-php:8.0"
    restart: "no"
    container_name: "project_${COMPOSE_NAME}"
    hostname: "${COMPOSE_HOSTNAME:-default}.chimera"
    environment:
      DDAP_LOGIN: ${DDAP_LOGIN:-}
      DDAP_PASSWORD: ${DDAP_PASSWORD:-}
      DDAP_DEVTOOLS: ${DDAP_DEVTOOLS:-}
    networks:
      chimera:
        aliases:
          - default.chimera
    volumes:
      # Do not map the whole root folder to avoid linux creating files into the repo
      - './.env:/root/.env'
      - './composer.json:/root/composer.json'
      - './composer.lock:/root/composer.lock'
      - './vendor:/root/vendor'
      # Map public
      - './public:/root/public'
      # Uploads are kept and synced
      - "${CHIMERA_KEEP}/public/uploads:/root/public/uploads"

networks:
  chimera:
    external: true
