version: "3.7"

services:

  {{name}}lap :
    image: "zouloux/docker-debian-apache-php:8.0"
    restart: "no"
    container_name: "project_${COMPOSE_NAME}"
    hostname: "${COMPOSE_HOSTNAME:-default}.chimera"
    environment:
      DDAP_LOGIN: ${DDAP_LOGIN:-}
      DDAP_PASSWORD: ${DDAP_PASSWORD:-}
      DDAP_DEVTOOLS: ${DDAP_DEVTOOLS:-}
    networks:
      - "chimera"
    volumes:
      - './:/root'
      - "${CHIMERA_KEEP}/public/uploads:/root/public/uploads"

networks:
  chimera:
    external: true
